[package]
name = "rust_prac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
globalenv = "0.4.2"
base64 = "0.21.0"
rand = "0.8.0"
nix = "0.26.2"
ctrlc = "3.2.4"